Hello Microverse project pull request
lengushuru/Hello-world-project pull request #1
Opened 2022-10-26 10:51 UTC by lengushuru

this is a setup of the Hello Microverse Project

2022-10-26 11:05 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @lengushuru, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - Linters set up correctly. ✔️
 - Correct use of Github flow. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [x] Your README file is a copy of the template Microverse provides. Please, customize the information inside the templated so the README represents this project and it looks more professional. Add information on the topics that are blank, change the information about the author, the issues link, the project title, and description, etc.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 11:05 UTC, leonardodiasb commented on index.html
> +</head>
- [ ] I see that you created a `styles.css` file but it was not imported into your HTML file, so the styling effects are not being applied to your project. Please import your CSS file so the style can be applied.

2022-10-26 13:21 UTC, fherrerao requested changes
Hi @lengushuru , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![So Close Snl GIF by Saturday Night Live](https://user-images.githubusercontent.com/91301423/197784121-950974af-5415-4bf0-871b-ce226a51ace4.gif)
 ## Highlights
✅ Greate use of GitHub flow.
✅ Good commit messages.
✅ No linter errors.

 ## Required Changes ♻️

- [ ] Please, as the previous reviewer says, you used the readme template but did not edit it with information related to your project (author, used technologies, etc. ). Please update the file and request a new review.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 15:08 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @lengushuru, 

Great work on making the changes requested by the previous reviewers 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
 -  No linter errors. :heavy_check_mark: 
 -   Correct GitHub  Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/77566116408d88259ddadf7605a02b67a4e825e002a39682ca5f2e8bca8c4d64/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [ ] You've not still implemented the request from one of the previous reviewers as regard your README file, Kindly attend to that and ask for another review. Thank you. :handshake:

2022-10-26 16:52 UTC, lengushuru commented on styles.css
> +}
@Qoosim should I request an extra review or should I make the changes you have pointed out only

2022-10-27 09:17 UTC, lengushuru commented
I have tried as much as I could to address the issues pointed out by the reviewers. please provide detailed issues that need to be addressed in the README.md file.

2022-10-27 09:37 UTC, fobadara commented on styles.css
> +}
Sorry about that. Your project should have been approved.
But I think you should delete the empty subheadings like setup and install

2022-10-27 09:39 UTC, fobadara approved these changes
Hi @lengushuru, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ Passing linters
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 10:13 UTC, merged